### ISSUE TITLE
AttributeError: 'XSSScanner' object has no attribute 'store_vulnerabilities_in_sqlite'

### ISSUE THREAD

**Issue by Archurcl4w** [haroonawanofficial/XSSInspector-SecurityToolkit#1]
Hello, I am testing xssinspector.py by cloning the repository and installing the required dependencies on Kali Linux 6.8.11-amd64
.After running a couple of minutes, it had errors such as
~~~
Traceback (most recent call last):
  File "/home/user/XSSInspector-SecurityToolkit/xssinspector.py", line 691, in <module>
    vulnerable_urls = scan.start()  # Start scanning for XSS vulnerabilities
                      ^^^^^^^^^^^^
  File "/home/user/XSSInspector-SecurityToolkit/xssinspector.py", line 616, in start
    self.store_vulnerabilities_in_sqlite()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'XSSScanner' object has no attribute 'store_vulnerabilities_in_sqlite'
~~~~
It indicated that the XSScanner class does not have the method called store_vulnerabilities_in_sqlite, but the Python code attempted to call it otherwise. It could cause 1. Missing Method and 2. Code Inconsistency. When looking at the XSScanner class in the xssinspector.py script and checking whether there is a method named store_vulnerabilities_in_sqlite by the command
~~~
grep "def store_vulnerabilities_in_sqlite" ~/XSSInspector-SecurityToolkit/xssinspector.py     
~~~
The output of this command returns blank. It shows that the method is missing or not properly implemented, but the script is supposed to store results in an SQLite database anyway. The only workaround at the moment is to comment out them.
~~~
# self.store_vulnerabilities_in_sqlite()
# self.generate_report()
~~~
After that, xssinspector.py running without errors until finishing the scan. But it failed to generate any reports as it should be. The fix could be reimplemented the method  store_vulnerabilities_in_sqlite and to work it properly. An example code of the missing method something like -
~~~
def store_vulnerabilities_in_sqlite(self):
        conn = sqlite3.connect('vulnerabilities.db')
        c = conn.cursor()
        c.execute('''
            CREATE TABLE IF NOT EXISTS vulnerabilities (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                url TEXT,
                payload TEXT,
                scan_time TEXT
            )
        ''')
        for url in self.vulnerable_urls:
            payload = 'xss_payload'
            start_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            c.execute('INSERT INTO vulnerabilities (url, payload, scan_time) VALUES (?, ?, ?)',
                      (url, payload, start_time))
        conn.commit()
        conn.close()

      
~~~~

**Comment by hendrafebriiiii** [comment]
this works sir?

> Halo, saya menguji xssinspector.py dengan mengkloning repositori dan menginstal dependensi yang diperlukan pada Kali Linux 6.8.11-amd64 . Setelah berjalan beberapa menit, muncul kesalahan seperti
> 
> ```
> Traceback (most recent call last):
>   File "/home/user/XSSInspector-SecurityToolkit/xssinspector.py", line 691, in <module>
>     vulnerable_urls = scan.start()  # Start scanning for XSS vulnerabilities
>                       ^^^^^^^^^^^^
>   File "/home/user/XSSInspector-SecurityToolkit/xssinspector.py", line 616, in start
>     self.store_vulnerabilities_in_sqlite()
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'XSSScanner' object has no attribute 'store_vulnerabilities_in_sqlite'
> ```
> 
> Hal ini menunjukkan bahwa kelas XSScanner tidak memiliki metode yang disebut store_vulnerabilities_in_sqlite, tetapi kode Python mencoba memanggilnya dengan cara lain. Hal ini dapat menyebabkan 1. Metode Hilang dan 2. Ketidakkonsistenan Kode. Saat melihat kelas XSScanner dalam skrip xssinspector.py dan memeriksa apakah ada metode bernama store_vulnerabilities_in_sqlite dengan perintah
> 
> ```
> grep "def store_vulnerabilities_in_sqlite" ~/XSSInspector-SecurityToolkit/xssinspector.py     
> ```
> 
> Output dari perintah ini mengembalikan kosong. Ini menunjukkan bahwa metode tersebut hilang atau tidak diterapkan dengan benar, tetapi skrip tersebut seharusnya menyimpan hasil dalam database SQLite. Satu-satunya solusi saat ini adalah mengomentarinya.
> 
> ```
> # self.store_vulnerabilities_in_sqlite()
> # self.generate_report()
> ```
> 
> Setelah itu, xssinspector.py berjalan tanpa kesalahan hingga pemindaian selesai. Namun gagal menghasilkan laporan sebagaimana mestinya. Perbaikannya dapat dilakukan dengan mengimplementasikan kembali metode store_vulnerabilities_in_sqlite dan membuatnya berfungsi dengan baik. Contoh kode metode yang hilang seperti -
> 
> ```
> def store_vulnerabilities_in_sqlite(self):
>         conn = sqlite3.connect('vulnerabilities.db')
>         c = conn.cursor()
>         c.execute('''
>             CREATE TABLE IF NOT EXISTS vulnerabilities (
>                 id INTEGER PRIMARY KEY AUTOINCREMENT,
>                 url TEXT,
>                 payload TEXT,
>                 scan_time TEXT
>             )
>         ''')
>         for url in self.vulnerable_urls:
>             payload = 'xss_payload'
>             start_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
>             c.execute('INSERT INTO vulnerabilities (url, payload, scan_time) VALUES (?, ?, ?)',
>                       (url, payload, start_time))
>         conn.commit()
>         conn.close()
> 
>       
> ```

**Comment by haroonawanofficial** [comment]
I will update it in a day

**Comment by haroonawanofficial** [comment]
STILL UNDER TESTING
==============
1. Work in progress with additional features and enhanced automation for XSSInspector, ensuring it will remain useful for the coming years.
2. Updates will be released after thorough testing on Windows, Ubuntu, and Kali.


![1](https://github.com/user-attachments/assets/5cf782ae-1d0c-4c5b-b313-61a89ddfde59)
![2](https://github.com/user-attachments/assets/61b57054-ca62-41af-a44b-8fe7842bf5a1)
![3](https://github.com/user-attachments/assets/bb081320-e147-49ad-96dc-bc2964437f2c)

**Comment by haroonawanofficial** [comment]
Updated Functionality Overview:

The updated logic follows these steps to enhance the effectiveness of the tool:

Extract URLs: The tool first extracts all URLs from the target web application.
Clean Extracted URLs: It then performs a cleaning operation on the extracted URLs to ensure no unnecessary or malformed entries remain.
Execute XSS Testing with Filters: Using the cleaned URLs, the tool proceeds to execute Cross-Site Scripting (XSS) attacks while applying relevant filters to detect vulnerabilities.
Generate Reports: The tool now includes a reporting option that generates detailed reports in HTML format for easy viewing and analysis.
Supported Technologies:

The tool has been enhanced to support the following technologies:

ASP
PHP
CGI
And more…
Advanced Heuristics:

The tool now incorporates advanced heuristics to automatically identify and add 10 common endpoints to URLs if they are not already present. This process ensures more thorough testing and better detection of potential vulnerabilities.

**Comment by haroonawanofficial** [comment]
please check the tool and let me know.
